wip work setup

diff --git a/home/dot_zshrc.tmpl b/home/dot_zshrc.tmpl
--- a/home/dot_zshrc.tmpl
+++ b/home/dot_zshrc.tmpl
@@ -19,10 +19,8 @@ eval "$(starship init zsh)"
 
 # https://docs.github.com/en/copilot/managing-copilot/configure-personal-settings/configuring-github-copilot-in-the-cli#zsh
 # If "gh copilot" fails echo a warning
-if ! gh copilot --version > /dev/null; then
-  echo "Warning: gh copilot is not installed or not configured properly."
-  echo "Run 'gh auth login' to configure GitHub CLI."
-  echo "Then, run 'gh extension install github/gh-copilot' to install the extension."
+if ! gh copilot --version > /dev/null 2>&1; then
+  echo "Cannot find GitHub Copilot CLI (https://docs.github.com/en/copilot/how-tos/set-up/install-copilot-cli)"
 else
   eval "$(gh copilot alias -- zsh)"
 fi
